### ISSUE TITLE
how to specify the pager?

### ISSUE THREAD

**Issue by c-cube** [fxfactorial/berber#1]
Seems like `berber foo` opens a pager (in my case, `less`) and gives it a string full of escape codes. In my case I would need to use `less -R` to properly display those, but I did not find an option for that.

**Comment by fxfactorial** [comment]
Oops forgot about the -R, added it in. 

I'm mainly doing it this way because I want syntax highlighting which is one of two choices I see, write quick small bindings to gnu source-highlight or use the command line. 

Do you think it would be smarter to open up pager choice to enduser?

**Comment by c-cube** [comment]
Well, `less -R` does it for me, so I'll close the issue, but it might be a good idea :-)
I'm going to add `build-doc` and `build-test` to my packages, incidentally, so you can replace `podge` with `containers` ;-)

**Comment by fxfactorial** [comment]
@c-cube if you are willing to do the PR to replace it, sure, I'll take it

**Comment by c-cube** [comment]
I was kidding. But still, you might find more things in `CCList` than in `Podge.List`, for instance.
